# Get All Job Offers
GET http://localhost:5000/job-offer/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDhiZDc5ZWE1ZmIzYTMyMGQ0NTFhMzYiLCJpYXQiOjE2ODY4ODc3MTQsImV4cCI6MTY4Njg5MTMxNH0.ZIHwuomKXVCakQWnvfwQFs47L7M9cepKzUOHSvZqPN0


###

# Get a Job Offer by ID
GET /api/job-offers/{id}

###

# Create a Job Offer
POST http://localhost:5000/job-offer/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDhiZDc5ZWE1ZmIzYTMyMGQ0NTFhMzYiLCJpYXQiOjE2ODY4ODc3MTQsImV4cCI6MTY4Njg5MTMxNH0.ZIHwuomKXVCakQWnvfwQFs47L7M9cepKzUOHSvZqPN0


{
  "title": "Job Offer Title",
  "description": "Job Offer Description",
  "creator": "648bda2f40ac81bf44a466ee",   
  "country": "Country Name",
  "city": "City Name",
  "location": "Location Details",
  "onsite": true,
  "requirements": ["Requirement 1", "Requirement 2"],
  "responsibilities": ["Responsibility 1", "Responsibility 2"],
  "contactLink": [
    {
      "name": "Link 1",
      "link": "https://example.com/link1"
    },
    {
      "name": "Link 2",
      "link": "https://example.com/link2"
    }
  ],
  "salaryRange": {
    "from": 5000,
    "to": 8000
  }
}

###

# Update a Job Offer
PUT /api/job-offers/{id}
Content-Type: application/json

{
  "title": "Updated Job Offer Title",
  "description": "Updated Job Offer Description",
  "creator": "60c982ec89a7340015d3c7be",
  "country": "Updated Country Name",
  "city": "Updated City Name",
  "location": "Updated Location Details",
  "onsite": false,
  "requirements": ["Updated Requirement 1", "Updated Requirement 2"],
  "responsibilities": ["Updated Responsibility 1", "Updated Responsibility 2"],
  "contactLink": [
    {
      "name": "Updated Link 1",
      "link": "https://example.com/updated-link1"
    },
    {
      "name": "Updated Link 2",
      "link": "https://example.com/updated-link2"
    }
  ],
  "salaryRange": {
    "from": 8000,
    "to": 12000
  }
}

###

# Delete a Job Offer
DELETE http://localhost:5000/job-offer/648be24ed2bc41dfc1869464
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDhiZDc5ZWE1ZmIzYTMyMGQ0NTFhMzYiLCJpYXQiOjE2ODY4ODc3MTQsImV4cCI6MTY4Njg5MTMxNH0.ZIHwuomKXVCakQWnvfwQFs47L7M9cepKzUOHSvZqPN0
