POST http://localhost:5000/user/register
Content-Type: application/json

{
  "email": "zaiyellyintaung@gmail.com",
  "password": "123",
  "isClient": true
}
###
POST http://localhost:5000/user/login
Content-Type: application/json

{
  "email": "zaiyellyintaung@gmail.com",
  "password": "123"
}